# Generated by Django 3.0.2 on 2020-07-08 08:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BpmnWorkflow',
            fields=[
                ('modified_by', models.CharField(max_length=128)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('workflow_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('bpmn', jsonfield.fields.JSONField(default=dict)),
                ('workflow_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0, help_text='Next Public Version')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfigResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_by', models.CharField(max_length=128)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('variable', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('modified_by', models.CharField(max_length=128)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_key', models.CharField(db_index=True, max_length=255)),
                ('task', models.CharField(db_index=True, max_length=255)),
                ('variable', jsonfield.fields.JSONField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('process_status', models.PositiveSmallIntegerField(choices=[(0, 'ERROR'), (2, 'PROCESSING'), (3, 'SUCCESS'), (4, 'WAITING_RESPONSE'), (1, 'WAITING_TO_PROCESS')], default=1)),
                ('status', models.PositiveSmallIntegerField(choices=[(4, 'COMPLETE'), (0, 'ERROR'), (2, 'PROCESSING'), (5, 'STOP_AT_FILTER'), (3, 'SUBJOB_COMPLETE'), (1, 'WAITING_TO_PROCESS')], default=1)),
                ('job_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_job', to='workflow_bpmn.Job')),
                ('job_root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_job', to='workflow_bpmn.Job')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_bpmn.BpmnWorkflow')),
            ],
            options={
                'unique_together': {('workflow', 'job_key')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_by', models.CharField(max_length=128)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.TextField(null=True)),
                ('method_type', models.TextField(choices=[('delete', 'DELETE'), ('get', 'GET'), ('head', 'HEAD'), ('options', 'OPTIONS'), ('patch', 'PATCH'), ('post', 'POST'), ('put', 'PUT')])),
                ('input_interface', jsonfield.fields.JSONField(blank=True, null=True)),
                ('output_interface', jsonfield.fields.JSONField(blank=True, null=True)),
                ('header', jsonfield.fields.JSONField(blank=True, null=True)),
                ('is_asynchronous', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobWaitingResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_by', models.CharField(max_length=128)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('task', models.CharField(db_index=True, max_length=255)),
                ('ref_id', models.CharField(db_index=True, max_length=255)),
                ('is_done', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_bpmn.Job')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_bpmn.BpmnWorkflow')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', jsonfield.fields.JSONField(blank=True, null=True)),
                ('task', models.CharField(db_index=True, max_length=255)),
                ('process_status', models.PositiveSmallIntegerField(choices=[(0, 'ERROR'), (2, 'PROCESSING'), (3, 'SUCCESS'), (4, 'WAITING_RESPONSE'), (1, 'WAITING_TO_PROCESS')], default=1)),
                ('modified_by', models.CharField(max_length=128)),
                ('modified_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='workflow_bpmn.Job')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_bpmn.BpmnWorkflow')),
            ],
        ),
        migrations.CreateModel(
            name='BpmnWorkflowVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpmn', jsonfield.fields.JSONField(default=dict)),
                ('note', models.TextField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('modified_by', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=False)),
                ('modified_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('workflow_id', models.ForeignKey(db_column='workflow_id', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='workflow_bpmn.BpmnWorkflow')),
            ],
        ),
        migrations.CreateModel(
            name='BpmnWorkflowController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_by', models.CharField(max_length=128)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('bpmn', picklefield.fields.PickledObjectField(editable=False)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('run', 'RUN'), ('error', 'RUN_ERROR'), ('starting', 'STARTING'), ('stopping', 'STOPPING'), ('terminate', 'TERMINATE')], db_index=True, default='pending', max_length=10)),
                ('config_resources', models.ManyToManyField(blank=True, null=True, to='workflow_bpmn.ConfigResource')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow_bpmn.BpmnWorkflowVersion')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_bpmn.BpmnWorkflow')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
