# Generated by Django 3.0.2 on 2020-08-26 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0012_periodictask_expire_seconds'),
        ('workflow_bpmn', '0002_jobwaitingresponse_gateway'),
    ]

    operations = [
        migrations.CreateModel(
            name='BpmnWorkflowPeriodic',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.PeriodicTask')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_bpmn.BpmnWorkflowController')),
            ],
            bases=('django_celery_beat.periodictask',),
        ),
    ]
