# Generated by Django 3.0.2 on 2020-09-03 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_bpmn', '0003_bpmnworkflowperiodic'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpmnworkflowperiodic',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow_bpmn.Job'),
        ),
    ]
