# Generated by Django 3.0.2 on 2020-11-03 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_bpmn', '0004_bpmnworkflowperiodic_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='workflow_version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflow_bpmn.BpmnWorkflowVersion'),
            preserve_default=False,
        ),
    ]
