# Generated by Django 3.1.3 on 2020-11-25 05:24

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_bpmn', '0007_auto_20201125_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionservice',
            name='data_interface',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
